FROM apache/spark:3.5.1

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir pyspark numpy pandas matplotlib

WORKDIR /app

COPY app.py /app/app.py
COPY kddcup.data /app/kddcup.data

COPY entrypoint-driver.sh /entrypoint-driver.sh
RUN chmod +x /entrypoint-driver.sh

ENTRYPOINT ["/entrypoint-driver.sh"]
